In [1]:
import numpy as np
import pandas as pd

In [7]:
i = np.array(range(10,0,-2))
np.resize(i,(5,5))

array([[10,  8,  6,  4,  2],
       [10,  8,  6,  4,  2],
       [10,  8,  6,  4,  2],
       [10,  8,  6,  4,  2],
       [10,  8,  6,  4,  2]])

In [8]:
i.resize((5,5), refcheck=False)
i

array([[10,  8,  6,  4,  2],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [21]:
j = np.array(range(4))
k = np.array(range(10,2,-2))
np.vstack([j,k])

array([[ 0,  1,  2,  3],
       [10,  8,  6,  4]])

In [22]:
np.hstack([j,k])

array([ 0,  1,  2,  3, 10,  8,  6,  4])

In [23]:
j+k

array([10,  9,  8,  7])

In [31]:
j/k

array([0.        , 0.125     , 0.33333333, 0.75      ])

In [29]:
j//k

array([0, 0, 0, 0])

In [32]:
j.dot(k)  #ضرب داخلی

32

In [35]:
i.shape

(5, 5)

In [36]:
i.T  #ترانهاده

array([[10,  0,  0,  0,  0],
       [ 8,  0,  0,  0,  0],
       [ 6,  0,  0,  0,  0],
       [ 4,  0,  0,  0,  0],
       [ 2,  0,  0,  0,  0]])

In [40]:
j.astype('f')

array([0., 1., 2., 3.], dtype=float32)

In [44]:
print(k.max())
print(k.argmax())

10
0


In [47]:
np.arange(4) ** 2

array([0, 1, 4, 9])

In [58]:
i[:,:]

array([[10,  8,  6,  4,  2],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [60]:
i[:,-2:] #from first go back

array([[4, 2],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [61]:
i[:,:-2] #from end go back

array([[10,  8,  6],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0]])

In [64]:
i[::-2,::2] #2 step 2 step moving backward and forward

array([[ 0,  0,  0],
       [ 0,  0,  0],
       [10,  6,  2]])

In [65]:
i >= 2

array([[ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])