In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
data = pd.read_csv('cardio_train1.csv')
data.head()

id    age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
0   0  18393       2     168    62.0    110     80            1     1      0   
1   1  20228       1     156    85.0    140     90            3     1      0   
2   2  18857       1     165    64.0    130     70            3     1      0   
3   3  17623       2     169    82.0    150    100            1     1      0   
4   4  17474       1     156    56.0    100     60            1     1      0   

   alco  active  cardio  
0     0       1       0  
1     0       1       1  
2     0       0       1  
3     0       1       1  
4     0       0       0

In [3]:
data.isna().sum()

id             0
age            0
gender         0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
cardio         0
dtype: int64

In [4]:
X = data.iloc[:, 1:-1]
y = data.iloc[:, -1]

In [5]:
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
X = mms.fit_transform(X)

In [6]:
X

array([[0.58807588, 1.        , 0.57948718, ..., 0.        , 0.        ,
        1.        ],
       [0.73015873, 0.        , 0.51794872, ..., 0.        , 0.        ,
        1.        ],
       [0.6240031 , 0.        , 0.56410256, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.64018583, 1.        , 0.65641026, ..., 0.        , 1.        ,
        0.        ],
       [0.90073558, 0.        , 0.55384615, ..., 0.        , 0.        ,
        0.        ],
       [0.75431669, 0.        , 0.58974359, ..., 0.        , 0.        ,
        1.        ]])

In [8]:
y

0        0
1        1
2        1
3        1
4        0
        ..
69995    0
69996    1
69997    1
69998    1
69999    0
Name: cardio, Length: 70000, dtype: int64

In [7]:
np.shape(X)

(70000, 11)

In [9]:
y = pd.get_dummies(y)
y

0  1
0      1  0
1      0  1
2      0  1
3      0  1
4      1  0
...   .. ..
69995  1  0
69996  0  1
69997  0  1
69998  0  1
69999  1  0

[70000 rows x 2 columns]

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=33123)

In [11]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(11, activation='relu', input_shape=(11,)),
    tf.keras.layers.Dense(30, activation='relu'),
    tf.keras.layers.Dense(2, activation='softmax')
])

In [12]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.001), loss=tf.keras.losses.CategoricalCrossentropy(), metrics=[tf.keras.metrics.CategoricalAccuracy()])

In [31]:
model.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test), batch_size=800)

Epoch 1/10
66/66 [==============================] - 0s 2ms/step - loss: 0.6249 - categorical_accuracy: 0.6495 - val_loss: 0.6288 - val_categorical_accuracy: 0.6447
Epoch 2/10
66/66 [==============================] - 0s 3ms/step - loss: 0.6249 - categorical_accuracy: 0.6490 - val_loss: 0.6293 - val_categorical_accuracy: 0.6435
Epoch 3/10
66/66 [==============================] - 0s 3ms/step - loss: 0.6248 - categorical_accuracy: 0.6493 - val_loss: 0.6278 - val_categorical_accuracy: 0.6451
Epoch 4/10
66/66 [==============================] - 0s 3ms/step - loss: 0.6244 - categorical_accuracy: 0.6510 - val_loss: 0.6276 - val_categorical_accuracy: 0.6438
Epoch 5/10
66/66 [==============================] - 0s 3ms/step - loss: 0.6240 - categorical_accuracy: 0.6502 - val_loss: 0.6274 - val_categorical_accuracy: 0.6455
Epoch 6/10
66/66 [==============================] - 0s 3ms/step - loss: 0.6239 - categorical_accuracy: 0.6498 - val_loss: 0.6270 - val_categorical_accuracy: 0.6451
Epoch 7/10
66/66

In [32]:
from sklearn.ensemble import RandomForestClassifier
yr = data.iloc[:, -1]

In [34]:
np.unique(yr, return_counts=True)

(array([0, 1]), array([35021, 34979]))

In [35]:
rfc = RandomForestClassifier(n_estimators=200)
Xr_train, Xr_test, yr_train, yr_test = train_test_split(X, yr, random_state=33123)

In [36]:
rfc.fit(Xr_train, yr_train)

RandomForestClassifier(n_estimators=200)

In [37]:
from sklearn.metrics import classification_report

In [38]:
y_pred = rfc.predict(Xr_test)
print(classification_report(y_true=yr_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.70      0.72      0.71      8652
           1       0.72      0.70      0.71      8848

    accuracy                           0.71     17500
   macro avg       0.71      0.71      0.71     17500
weighted avg       0.71      0.71      0.71     17500



In [17]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(11, activation='relu', input_shape=(11,)),
    tf.keras.layers.Dense(15, activation='relu'),
    tf.keras.layers.Dense(25, activation='relu'),
    tf.keras.layers.Dense(35, activation='relu'),
    tf.keras.layers.Dense(2, activation='softmax')
])
model.compile(optimizer=tf.keras.optimizers.Adam(0.001), loss=tf.keras.losses.CategoricalCrossentropy(), metrics=[tf.keras.metrics.CategoricalAccuracy()])

In [18]:
model.fit(X_train, y_train, epochs=300, validation_data=(X_test, y_test))

Epoch 1/300
1641/1641 [==============================] - 9s 4ms/step - loss: 0.6446 - categorical_accuracy: 0.6255 - val_loss: 0.6435 - val_categorical_accuracy: 0.6270
Epoch 2/300
1641/1641 [==============================] - 7s 4ms/step - loss: 0.6330 - categorical_accuracy: 0.6396 - val_loss: 0.6329 - val_categorical_accuracy: 0.6386
Epoch 3/300
1641/1641 [==============================] - 7s 4ms/step - loss: 0.6297 - categorical_accuracy: 0.6434 - val_loss: 0.6309 - val_categorical_accuracy: 0.6398
Epoch 4/300
1641/1641 [==============================] - 7s 4ms/step - loss: 0.6276 - categorical_accuracy: 0.6460 - val_loss: 0.6297 - val_categorical_accuracy: 0.6427
Epoch 5/300
1641/1641 [==============================] - 8s 5ms/step - loss: 0.6267 - categorical_accuracy: 0.6467 - val_loss: 0.6288 - val_categorical_accuracy: 0.6434
Epoch 6/300
1641/1641 [==============================] - 10s 6ms/step - loss: 0.6262 - categorical_accuracy: 0.6482 - val_loss: 0.6274 - val_categorical_ac

KeyboardInterrupt: 

In [15]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 11)                132       
                                                                 
 dense_4 (Dense)             (None, 20)                240       
                                                                 
 dense_5 (Dense)             (None, 10)                210       
                                                                 
 dense_6 (Dense)             (None, 15)                165       
                                                                 
 dense_7 (Dense)             (None, 2)                 32        
                                                                 
Total params: 779
Trainable params: 779
Non-trainable params: 0
_________________________________________________________________


In [16]:
model.predict(X_test)[3]

547/547 [==============================] - 2s 2ms/step


array([0.5301521 , 0.46984795], dtype=float32)