In [1]:
import numpy

In [4]:
vector = [1, 2, 3]

In [5]:
print(type(vector))

<class 'list'>


In [6]:
nvector = numpy.array(vector)

In [7]:
nvector.shape

(3,)

In [8]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [9]:
nmatrix = numpy.array(matrix)

In [10]:
nmatrix.shape

(3, 3)

In [11]:
j = 3
i = [1, 2, 3]
k = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
x = [
    [[1, 2, 3], [6, 2, 3], [8, 4, 2]],
    [[5, 2, 3], [6, 2, 3], [8, 4, 2]],
    [[1, 7, 3], [6, 2, 3], [8, 4, 2]],
]

In [12]:
narr = numpy.array([1, 2, 3])
narr

array([1, 2, 3])

In [13]:
numpy.resize(narr, (4, 4))

array([[1, 2, 3, 1],
       [2, 3, 1, 2],
       [3, 1, 2, 3],
       [1, 2, 3, 1]])

In [14]:
narr.resize((3, 3), refcheck=False)

In [15]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [16]:
matrix = numpy.ones((5, 4))

In [17]:
matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
matrix = numpy.zeros((4, 4))
matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
numpy.diag(narr)

array([1, 0, 0])

In [20]:
numpy.repeat([4, 3, 2], 5)

array([4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2])

In [21]:
m1 = numpy.ones((4, 5), int)
m1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
m2 = numpy.zeros((4, 3), int)
m2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
numpy.vstack([m1, m2])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 3

In [ ]:
numpy.hstack([m1, m2])

array([[1, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0]])

In [ ]:
x = numpy.array([1, 2, 3])
y = numpy.array([4, 5, 5])


In [ ]:
z = x * y
z

array([ 4, 10, 15])

In [ ]:
x ** 2

array([1, 4, 9])

In [ ]:
x.dot(y)

29

In [ ]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
narr.T

array([[1, 0, 0],
       [2, 0, 0],
       [3, 0, 0]])

In [ ]:
narr.astype('f')

array([[1., 2., 3.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [ ]:
narr.sum()

6

In [ ]:
narr.max()

3

In [ ]:
narr.min()

0

In [ ]:
narr.argmax()

2

In [ ]:
narr.argmin()

3

In [ ]:
narr.mean()

0.6666666666666666

In [ ]:
narr.std()

1.0540925533894598

In [ ]:
mr = numpy.arange(15) ** 2
mr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [ ]:
mr[2]

4

In [ ]:
mr[1:5]

array([ 1,  4,  9, 16])

In [ ]:
mr[:5]

array([ 0,  1,  4,  9, 16])

In [ ]:
mr[-2:]

array([169, 196])

In [ ]:
mr[10::-2]

array([100,  64,  36,  16])

In [ ]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
narr[0:2, 1:3]

array([[2, 3],
       [0, 0]])

In [ ]:
narr[::2, -1]

array([3, 0])

In [ ]:
narr[narr >= 2]

array([2, 3])

In [ ]:
narr >= 2

array([[False,  True,  True],
       [False, False, False],
       [False, False, False]])

In [ ]:
marr = narr[-1]
marr

array([0, 0, 0])

In [ ]:
marr[:] = 1
marr

array([1, 1, 1])

In [ ]:
marr[:2] = 2
marr

array([2, 2, 1])

In [ ]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [25]:
marr = narr.copy()
marr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [26]:
marr[:] = 0
marr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [27]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
tarr = numpy.random.randint(0, 10, (4, 3))
tarr

array([[0, 2, 1],
       [6, 0, 9],
       [2, 8, 1],
       [2, 3, 1]])

In [ ]:
for r in tarr:
    r = r ** 2
    print(r)

[0 4 1]
[36  0 81]
[ 4 64  1]
[4 9 1]


In [ ]:
for i, r in enumerate(tarr):
    print('index(' + str(i) + ') is ', r)

index(0) is  [0 2 1]
index(1) is  [6 0 9]
index(2) is  [2 8 1]
index(3) is  [2 3 1]


In [ ]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [ ]:
marr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [29]:
list(zip(narr, marr,'ab'))

[(array([1, 2, 3]), array([0, 0, 0]), 'a'),
 (array([0, 0, 0]), array([0, 0, 0]), 'b')]

In [31]:
arr = [1, 4, 2, 9, 8, 6, 3]
arr = numpy.array(arr)
arr

array([1, 4, 2, 9, 8, 6, 3])

In [32]:
len(arr) // 2

3

In [33]:
p = arr[len(arr) // 2]
p

9

In [35]:
arr

array([1, 4, 2, 9, 8, 6, 3])

In [ ]:
l = [x for x in arr if x  < p]
l

[1, 4, 2, 8, 6, 3]

In [ ]:
r = [x for x in arr if x > p]
r

[]

In [ ]:
m = [x for x in arr if x == p]
m

[9]

In [ ]:
l + m + r

[1, 4, 2, 8, 6, 3, 9]

In [2]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    arr = numpy.array(arr)
    p = arr[len(arr) // 2]
    l = [x for x in arr if x  < p]
    m = [x for x in arr if x == p]
    r = [x for x in arr if x > p]
    return quicksort(l) + m + quicksort(r)

In [23]:
a = []
for i in range(1000000,0,-1):
    a.append(i)
a.sort()
a = quicksort(a)