In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('DataPreprocessing.csv')
data

Region   Age   Income Online Shopper
0   India  49.0  86400.0             No
1  Brazil  32.0  57600.0            Yes
2     USA  35.0  64800.0             No
3  Brazil  43.0  73200.0             No
4     USA  45.0      NaN            Yes
5   India  40.0  69600.0            Yes
6  Brazil   NaN  62400.0             No
7   India  53.0  94800.0            Yes
8     USA  55.0  99600.0             No
9   India  42.0  80400.0            Yes

In [3]:
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [4]:
from sklearn.impute import SimpleImputer

In [5]:
si = SimpleImputer(missing_values=np.nan, strategy='mean')
si.fit(X[:, 1:])
X[:, 1:] = si.transform(X[:, 1:])

In [6]:
X

array([['India', 49.0, 86400.0],
       ['Brazil', 32.0, 57600.0],
       ['USA', 35.0, 64800.0],
       ['Brazil', 43.0, 73200.0],
       ['USA', 45.0, 76533.33333333333],
       ['India', 40.0, 69600.0],
       ['Brazil', 43.77777777777778, 62400.0],
       ['India', 53.0, 94800.0],
       ['USA', 55.0, 99600.0],
       ['India', 42.0, 80400.0]], dtype=object)

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
le = LabelEncoder()
X[:, 0] = le.fit_transform(X[:, 0])
X

array([[1, 49.0, 86400.0],
       [0, 32.0, 57600.0],
       [2, 35.0, 64800.0],
       [0, 43.0, 73200.0],
       [2, 45.0, 76533.33333333333],
       [1, 40.0, 69600.0],
       [0, 43.77777777777778, 62400.0],
       [1, 53.0, 94800.0],
       [2, 55.0, 99600.0],
       [1, 42.0, 80400.0]], dtype=object)

In [9]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [10]:
ct = ColumnTransformer([('Country', OneHotEncoder(), [0])], remainder='passthrough')
X = ct.fit_transform(X)
X

array([[0.0, 1.0, 0.0, 49.0, 86400.0],
       [1.0, 0.0, 0.0, 32.0, 57600.0],
       [0.0, 0.0, 1.0, 35.0, 64800.0],
       [1.0, 0.0, 0.0, 43.0, 73200.0],
       [0.0, 0.0, 1.0, 45.0, 76533.33333333333],
       [0.0, 1.0, 0.0, 40.0, 69600.0],
       [1.0, 0.0, 0.0, 43.77777777777778, 62400.0],
       [0.0, 1.0, 0.0, 53.0, 94800.0],
       [0.0, 0.0, 1.0, 55.0, 99600.0],
       [0.0, 1.0, 0.0, 42.0, 80400.0]], dtype=object)

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
ss = StandardScaler()
X = ss.fit_transform(X)

In [16]:
X

array([[-6.54653671e-01,  1.22474487e+00, -6.54653671e-01,
         7.58874362e-01,  7.49473254e-01],
       [ 1.52752523e+00, -8.16496581e-01, -6.54653671e-01,
        -1.71150388e+00, -1.43817841e+00],
       [-6.54653671e-01, -8.16496581e-01,  1.52752523e+00,
        -1.27555478e+00, -8.91265492e-01],
       [ 1.52752523e+00, -8.16496581e-01, -6.54653671e-01,
        -1.13023841e-01, -2.53200424e-01],
       [-6.54653671e-01, -8.16496581e-01,  1.52752523e+00,
         1.77608893e-01, -3.60822483e-16],
       [-6.54653671e-01,  1.22474487e+00, -6.54653671e-01,
        -5.48972942e-01, -5.26656882e-01],
       [ 1.52752523e+00, -8.16496581e-01, -6.54653671e-01,
         8.88178420e-17, -1.07356980e+00],
       [-6.54653671e-01,  1.22474487e+00, -6.54653671e-01,
         1.34013983e+00,  1.38753832e+00],
       [-6.54653671e-01, -8.16496581e-01,  1.52752523e+00,
         1.63077256e+00,  1.75214693e+00],
       [-6.54653671e-01,  1.22474487e+00, -6.54653671e-01,
        -2.58340208e-01